services:

  php:
    build:
      context: .
      dockerfile: ./docker/php.Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./src:/var/www/html

  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server
    volumes:
      - ./redis:/data

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
